name: Publish ApplicationRecord to Registry
on:
  release:
    types: [published]
jobs:
  cns_publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone project repository"
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Install Yarn"
        run: npm install -g yarn
      - name: "Install registry CLI"
        run: |
          npm config set @cerc-io:registry https://git.vdb.to/api/packages/cerc-io/npm/
          yarn global add @cerc-io/laconic-registry-cli
      - name: "Install jq"
        run: apt -y update && apt -y install jq
      - name: "Publish Application Record"
        env:
          CERC_REGISTRY_USER_KEY: ${{ secrets.CICD_CERCIO_USER_KEY }}
          CERC_REGISTRY_BOND_ID: ${{ secrets.CICD_CERCIO_BOND_ID }}
          CERC_REGISTRY_APP_CRN: "crn://cerc-io/applications/test-progressive-web-app"
        run: scripts/publish-app-record.sh
      - name: "Request Deployment"
        env:
          CERC_REGISTRY_USER_KEY: ${{ secrets.CICD_LACONIC_USER_KEY }}
          CERC_REGISTRY_BOND_ID: ${{ secrets.CICD_LACONIC_BOND_ID }}
          CERC_REGISTRY_APP_CRN: "crn://cerc-io/applications/test-progressive-web-app"
        run: scripts/request-app-deployment.sh
