name: Publish ApplicationRecord to Registry
on:
  release:
    types: [published]
  push:
    branches:
      - main

env:
  CERC_REGISTRY_USER_KEY: ${{ secrets.CICD_LACONIC_USER_KEY }}
  CERC_REGISTRY_BOND_ID: ${{ secrets.CICD_LACONIC_BOND_ID }}

jobs:
  cns_publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone project repository"
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: "Install exiftool"
        run: |
          echo "hi hello"
          apt-get update -y
          apt-get upgrade -y
          apt-get install exiftool -y
      - name: "Install Yarn"
        run: npm install -g yarn
      - name: "Install registry CLI"
        run: |
          npm config set @cerc-io:registry https://git.vdb.to/api/packages/cerc-io/npm/
          yarn global add @cerc-io/laconic-registry-cli
      - name: "Install jq"
        uses: dcarbone/install-jq-action@v2.1.0
      - name: "Publish Application Record"
        run: scripts/publish-app-record.sh
      - name: "Request Deployment"
        run: scripts/request-app-deployment.sh
